- id: convert-notebooks
  name: convert-notebooks
  description: Convert all notebooks into another format, output will be tracked
  language: python
  entry: jupytext --pre-commit
  pass_filenames: false
  files: .ipynb
  args:
    - --to
    - py:percent

- id: unstage-notebooks
  name: unstage-notebooks
  description: Unstage any staged notebooks, changes will not be committed
  language: python
  files: .ipynb
  entry: git reset HEAD --

- id: remove-notebooks
  name: remove-notebooks
  description: Remove any committed notebooks, they will no longer be tracked
  language: python
  files: .ipynb
  entry: git rm --cached --
