- id: jupytext
  name: jupytext
  description: Convert all notebooks into another format, output will be tracked
  language: python
  entry: jupytext --pre-commit
  pass_filenames: false
  args:
    - --to
    - py:percent
