- id: jupytext
  name: jupytext
  description: Convert all notebooks into another format
  language: python
  entry: jupytext --add-untracked
  pass_filenames: true
  files: ipynb
  args:
    - --to
    - py:percent
